In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]
mylist1 = np.array(mylist)

In [3]:
mylist1

array([1, 2, 3, 4])

In [4]:
mylist2 = [10,11,12,13]

In [5]:
mylist2

[10, 11, 12, 13]

In [6]:
mylists = [mylist1, mylist2]

In [7]:
mylists

[array([1, 2, 3, 4]), [10, 11, 12, 13]]

In [8]:
my_array = np.array(mylists)

In [9]:
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [10]:
my_array.shape

(2, 4)

In [11]:
my_array.dtype

dtype('int64')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5).dtype

dtype('float64')

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [14]:
import pandas as pd

In [15]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2